JumpscaleLib/clients/zero_boot/ZerobootClient.py

Improve zeroboot client parsing

Improve zeroboot client parsing

---

JumpscaleLib/clients/gdrive/GDrive.py
JumpscaleLib/clients/gdrive/GDriveFile.py
JumpscaleLib/clients/ovh/OVHClient.py
JumpscaleLib/data/capnp/Capnp.py
JumpscaleLib/data/capnp/ModelBase.py
JumpscaleLib/data/capnp/ModelBaseCollection.py
JumpscaleLib/data/flist/FList.py
JumpscaleLib/data/flist/FListMetadata.py
JumpscaleLib/sal/btrfs/BtrfsExtension.py
JumpscaleLib/tools/docsite/DocSite.py
JumpscaleLib/tools/docsite/DocSites.py

part of https://github.com/threefoldtech/jumpscale_core/issues/81

fix call to js exception

---

JumpscaleLib/sal_zos/gateway/gateway.py
JumpscaleLib/sal_zos/network/Network.py
JumpscaleLib/sal_zos/node/Node.py

required for https://github.com/threefoldtech/0-templates/issues/81

add support for routes in gateway sal

---

JumpscaleLib/tools/sandboxer/SandboxPython.py
JumpscaleLib/tools/sandboxer/Sandboxer.py

Fix Redis installiation in Mac platform #92

fix redis installiation in OSX version

---

JumpscaleLib/clients/blockchain/rivine/RivineClient.py

Close #89 
If no seed is given, one is generated and saved the first time the wallet will be accessed

Make seed optional in rivine

---

JumpscaleLib/clients/blockchain/rivine/RivineClient.py
JumpscaleLib/clients/blockchain/tfchain/README.md
JumpscaleLib/clients/blockchain/tfchain/TfchainClient.py
JumpscaleLib/clients/blockchain/tfchain/TfchainClientFactory.py
JumpscaleLib/clients/blockchain/tfchain/TfchainMultiSigWallet.py
JumpscaleLib/clients/blockchain/tfchain/TfchainWallet.py
JumpscaleLib/clients/blockchain/tfchain/atomicswap/atomicswap.py
JumpscaleLib/clients/blockchain/tfchain/const.py
JumpscaleLib/clients/blockchain/tfchain/encoding/binary.py
JumpscaleLib/clients/blockchain/tfchain/errors.py
JumpscaleLib/clients/blockchain/tfchain/merkletree.py
JumpscaleLib/clients/blockchain/tfchain/secrets.py
JumpscaleLib/clients/blockchain/tfchain/types/signatures.py
JumpscaleLib/clients/blockchain/tfchain/types/transaction.py
JumpscaleLib/clients/blockchain/tfchain/types/unlockconditions.py
JumpscaleLib/clients/blockchain/tfchain/types/unlockhash.py
JumpscaleLib/clients/blockchain/tfchain/utils.py

-
-
**Version**: 
**Fixes**: #

Port tfchain client

---

tests/integration_tests/framework/base/vdisk.py
tests/integration_tests/testcases/base_test.py
tests/integration_tests/testcases/test03_vdisk.py

add vdisk test cases

---

JumpscaleLib/clients/blockchain/tfchain/README.md
JumpscaleLib/clients/blockchain/tfchain/TfchainClientFactory.py

-Add Create and open wallet convenience methods
**Version**: 
**Fixes**: #90

Add Create and open wallet convenience methods 

---

JumpscaleLib/clients/blockchain/rivine/RivineWallet.py
JumpscaleLib/clients/blockchain/tfchain/README.md

Expose current minter definition

---

JumpscaleLib/clients/blockchain/rivine/RivineWallet.py

-
-
**Version**: 
**Fixes**: #

Multisig spending support

---

JumpscaleLib/clients/blockchain/rivine/errors.py
JumpscaleLib/clients/blockchain/tfchain/TfchainClientFactory.py

-
-
**Version**: 
**Fixes**: #

Raise error when trying to create a wallet with an already existing name

---

JumpscaleLib/clients/blockchain/rivine/errors.py

Signed-off-by: Rob Van Mieghem <robvanmieghem@gmail.com>
-
-
**Version**: 
**Fixes**: #

Better errormessage in case a rivine wallet already exists

---

JumpscaleLib/clients/blockchain/rivine/utils.py

Fixes: https://github.com/threefoldtech/jumpscale_lib/issues/178

fix a bug with unconfirmed transactions

---

JumpscaleLib/clients/blockchain/rivine/RivineWallet.py

https://github.com/threefoldtech/jumpscale_lib/issues/88

update address generation

---

JumpscaleLib/clients/blockchain/rivine/RivineWallet.py

**Fixes**: https://github.com/threefoldtech/jumpscale_lib/issues/182

fix wallet balance

---

JumpscaleLib/sal_zos/minio/Minio.py
JumpscaleLib/sal_zos/minio/MinioFactory.py
JumpscaleLib/sal_zos/minio/Minio_test.py
JumpscaleLib/sal_zos/templates/minio.conf

https://github.com/threefoldtech/0-templates/issues/148

Allow configuring master log in minio

---

JumpscaleLib/sal_zos/disks/Partition.py
JumpscaleLib/sal_zos/node/Node.py
JumpscaleLib/sal_zos/storage/StoragePool.py
JumpscaleLib/sal_zos/zerodb/__init__.py

-
-
**Version**: 
**Fixes**: #

Refactor storagepool

---

JumpscaleLib/sal_zos/container/Container.py
JumpscaleLib/sal_zos/network/Network.py

-
-
**Version**: 
**Fixes**: #

Development network deconfigure

---

tests/integration_tests/framework/base/vms.py
tests/integration_tests/testcases/advanced/test01_zdb.py
tests/integration_tests/testcases/base_test.py
tests/integration_tests/testcases/test01_vms.py
tests/integration_tests/testcases/test04_zdb.py

- add mount to vm testcase.
- add config to vm testcase.
- edit zdb mount path.
- edit disk info.

Add vm testcase

---

JumpscaleLib/sal/traefik/TraefikClient.py
JumpscaleLib/sal/traefik/encoding.py
JumpscaleLib/sal/traefik/types.py
JumpscaleLib/sal/webgateway/README.md
JumpscaleLib/sal/webgateway/WebGatewayFactory.py
JumpscaleLib/sal/webgateway/errors.py
JumpscaleLib/sal/webgateway/service.py
JumpscaleLib/sal/webgateway/webgateway.py

add webgateway sal

---

JumpscaleLib/servers/grid_capacity/server/templates/capacity.html

Hide negative available resource on the capacity

Do not show negative available value on capacity grid

---

JumpscaleLib/clients/zerotier/ZerotierClient.py

the old get_private_ip method doesn't accurate enough to measure timeout
and btw, `while timout` will be forever unless timout=0, so if the `timout=Odd_numeber` this will stuck forever

Fix get private ip zt client

---

JumpscaleLib/sal_zos/container/Container.py
JumpscaleLib/sal_zos/globals.py
JumpscaleLib/sal_zos/minio/Minio.py

-
-
**Version**: 
**Fixes**: #

increase timeout to get ZT ip

---

JumpscaleLib/clients/zerotier/ZerotierClient.py

add logs to track zerotier client actions

zt client logs

---

JumpscaleLib/clients/zerotier/ZerotierClient.py
JumpscaleLib/sal_zos/globals.py

change fixed timeout to be TIMEOUT_DEPLOY

change fixed timeout to be TIMEOUT_DEPLOY

---

JumpscaleLib/sal_zos/vm/ZOS_VM.py

Adding kvm param while creating vm to support nested vms
**Version**:  development

Add kvm param to vm creation to support nested vms

---

JumpscaleLib/sal_zos/container/Container.py

try to use the new container.get command when using the sal to get a container by name

Container get improvement

---

JumpscaleLib/servers/grid_capacity/server/flask_itsyouonline.py
JumpscaleLib/servers/grid_capacity/server/frontend_blueprint.py
JumpscaleLib/servers/grid_capacity/server/handlers/RegisterCapacityHandler.py
JumpscaleLib/servers/grid_capacity/server/handlers/RegisterFarmerHandler.py
JumpscaleLib/servers/grid_capacity/server/handlers/UpdateReservedCapacityHandler.py
JumpscaleLib/servers/grid_capacity/server/templates/capacity.html
JumpscaleLib/servers/grid_capacity/server/templates/farm_get_id.html
JumpscaleLib/servers/grid_capacity/server/templates/farmers.html
JumpscaleLib/servers/grid_capacity/server/templates/layout.html

- New interface features:
- Regenerate a Farmer ID for your farm
- Button changes
- Home page more compact
- Fix Login/Logout not properly handled sometime
- Fix possibility to create empty farmer (cause bug with empty id)
- Fix exception not catched when pushing data to non-existing node into database
- Fix exception on invalid farmer (maybe still have issue)
- Improve session persistance

Improve Capacity Server

---

JumpscaleLib/sal_zos/capacity/Capacity.py
JumpscaleLib/servers/grid_capacity/server/handlers/GetCapacityHandler.py
JumpscaleLib/servers/grid_capacity/server/handlers/ListCapacityHandler.py
JumpscaleLib/servers/grid_capacity/server/handlers/RegisterCapacityHandler.py
JumpscaleLib/servers/grid_capacity/server/handlers/schema/Capacity_schema.json
JumpscaleLib/servers/grid_capacity/server/models.py

Add support for hardware dump in directory

Directory update

---

JumpscaleLib/sal_zos/templates/tf_explorer_caddy.conf

Port changes done in https://github.com/threefoldfoundation/tfchain/commit/fb137035988667f275656b8f622cea99382ac99f

Allow all headers in CORS request on explorer
